version: '2'


services:
  web:
    container_name: test_web
    image: node
    depends_on:
      - src
      - mongo
    links:
      - mongo:db.do5173.com
    ports:
      - "8000:8000"
    volumes_from:
      - src
    networks:
      - front-tier
      - back-tier
    working_dir: /app
    command: node index.js

  src:
    container_name: test_src
    image: node
    volumes:
      - ~/Documents/test/nodejs:/app
    working_dir: /
    command: git clone https://github.com/xuming314/test.git

  mongo:
    container_name: test_mongo
    image: mongo
    networks:
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge